### ISSUE TITLE
Remove AWS provider definition from module

### ISSUE THREAD

**Issue by jaredready** [etleap/terraform-aws-etleap-vpc#9]
This module defines an AWS provider [here](https://github.com/etleap/terraform-aws-etleap-vpc/blob/master/provider.tf#L19-L26). This goes against HashiCorp's recommended practices [here](https://developer.hashicorp.com/terraform/language/modules/develop/providers)
> A module intended to be called by one or more other modules must not contain any provider blocks. A module containing its own provider configurations is not compatible with the for_each, count, and depends_on arguments that were introduced in Terraform v0.13. For more information, see [Legacy Shared Modules with Provider Configurations](https://developer.hashicorp.com/terraform/language/modules/develop/providers#legacy-shared-modules-with-provider-configurations).

This is causing issues with how we run Terraform, requiring workarounds just to use this module. Since the provider defined in this module doesn't appear to be doing anything unique, it should be able to be removed with little issue.

**Comment by romming** [comment]
Thanks for the note, @jaredready! We'll take a look and get back to you.

**Comment by romming** [comment]
Hi @jaredready - we are pretty sure we can get rid of the provider definition, just need to make sure we can apply the tags to all the resources. For our edification, could you please summarize the issues you're facing that are caused by the provider definition being there?

**Comment by jaredready** [comment]
Sure thing!

We run our Terraform through GitHub Actions and we have lots of AWS accounts. We have a role in a centralized account that GitHub Actions assumes and then we configure our AWS providers to assume the appropriate role for whatever account we're needing to deploy into.

gha-workflow.yaml
```yaml
...
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::999999999:role/gha-oidc-role
          aws-region: us-west-2
...
```

```hcl
provider "aws" {
  region = "us-west-2"
  assume_role {
    role_arn = "arn:aws:iam::0123456789:role/terraform-role"
  }
}
```

The module definition also having an AWS provider defined means our provider credentials get overwritten for all resources in that module, which results in resources being created in the wrong account.

For example when using this module and the account IDs above, our resources end up deployed into account `999999999` instead of `0123456789` where we intended them.

**Comment by romming** [comment]
Thanks for the quick response, @jaredready ! I'm probably missing something obvious, but given that our provider doesn't specify a role to be assumed, that's not a problem here, right? If so, would you mind sharing the issue you're having to work around?

**Comment by jaredready** [comment]
@romming 
> given that our provider doesn't specify a role to be assumed, that's not a problem here, right?

The problem is that a default provider configuration like this will just follow the normal credential lookup process. In this case, it uses the credentials assumed via OIDC in the GitHub Actions workflow but _not_ the credentials configured in the calling Terraform.

Referencing my example above...
```yaml
...
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::999999999:role/gha-oidc-role
          aws-region: us-west-2
...
```

```hcl
provider "aws" {
  region = "us-west-2"
  assume_role {
    role_arn = "arn:aws:iam::0123456789:role/terraform-role"
  }
}
```

When calling this module, the AWS provider defined within the module (the problematic one I'm requesting to be removed) ends up using the `arn:aws:iam::999999999:role/gha-oidc-role` credentials and _not_ the `arn:aws:iam::0123456789:role/terraform-role` credentials like we would want. 

If we remove the AWS provider from within this module, then the AWS provider configured in the _calling_ module is what gets used when provisioning AWS resources.
